INSERT INTO origem_mercadoria (id_origem, ds_origem)
                     VALUES ('0', 'NACIONAL, EXCETO AS INDICADAS NOS CÓDIGOS 3 A 5');
INSERT INTO origem_mercadoria (id_origem, ds_origem)
                     VALUES ('1', 'ESTRANGEIRA, IMPORTAÇÃO DIRETA, EXCETO A INDICADA NO CÓDIGO 6');
INSERT INTO origem_mercadoria (id_origem, ds_origem)
                     VALUES ('2', 'ESTRANGEIRA, ADQUIRIDA NO MERCADO INTERNO, EXCETO A INDICADA NO CÓDIGO 7');
INSERT INTO origem_mercadoria (id_origem, ds_origem)
                     VALUES ('3', 'NACIONAL, MERCADORIA OU BEM COM CONTEÚDO DE IMPORTAÇÃO SUPERIOR A 40%');
INSERT INTO origem_mercadoria (id_origem, ds_origem)
                     VALUES ('4', 'NACIONAL, CUJA PRODUÇÃO TENHA SIDO FEITA EM CONFORMIDADE COM OS PROCESSOS PRODUTIVOS BÁSICOS DE QUE TRATAM O DECRETO-LEI Nº 288/67 E AS LEIS NºS 8.248/91, 8.387/91, 10.176/01 E 11.484/07');
INSERT INTO origem_mercadoria (id_origem, ds_origem)
                     VALUES ('5', 'NACIONAL, MERCADORIA OU BEM COM CONTEÚDO DE IMPORTAÇÃO INFERIOR OU IGUAL A 40%');
INSERT INTO origem_mercadoria (id_origem, ds_origem)
                     VALUES ('6', 'ESTRANGEIRA, IMPORTAÇÃO DIRETA, SEM SIMILAR NACIONAL, CONSTANTE EM LISTA DE RESOLUÇÃO CAMEX');
INSERT INTO origem_mercadoria (id_origem, ds_origem)
                     VALUES ('7', ' ESTRANGEIRA, ADQUIRIDA NO MERCADO INTERNO, SEM SIMILAR NACIONAL, CONSTANTE EM LISTA DE RESOLUÇÃO CAMEX');
INSERT INTO origem_mercadoria (id_origem, ds_origem)
                     VALUES ('8', 'NACIONAL, MERCADORIA COM CONTEÚDO DE IMPORTAÇÃO IGUAL OU SUPERIOR A 70% ');